name: Comment lcov Code Coverage Report
description: Comments on a pull request with a lcov code coverage report
author: Steffen Koette
branding:
  icon: check-square
  color: green
inputs:
  github-token:
    description: Github token
    required: true
  pr-number:
    descirption: Number of the Pull Request
    required: true
  lcov-file:
    description: The location of the lcov.info file
    required: false
  lcov-base:
    description: The location of the lcov file for the base branch
    required: false
  hide-branch-coverage:
    description: Hides the branch coverage in the output if set to true
    required: false
  output-file:
    description: Filename to output result to, instead of posting a comment
    required: false


runs:
  using: node12
  main: dist/main.js
