name: Self Tests
on:
  pull_request:
    branches: [ master ]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Self test basic comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: test-resources/lcov.info
          pr-number: ${{ github.event.pull_request.number }}
  file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Self test file output
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: test-resources/lcov.info
          pr-number: ${{ github.event.pull_request.number }}
          output-file: test.html
      - name: 'Compare Output'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var fs = require('fs').promises;
            const expectedTemplate = await fs.readFile("test-resources/comment.html", "utf-8");
            const expected = expectedTemplate.replace("XXX", "${{github.event.pull_request.head.ref }}")
              .replace("YYY", "${{github.event.pull_request.base.ref }}")
              .replace(/ZZZ/g, "${{github.event.pull_request.head.sha }}");
            const got = await fs.readFile("test.html", "utf-8");
            console.log(expected == got)
            console.log(expected)
            console.log(got)
  hide-branch-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Self test no branch coverage in file
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: test-resources/lcov.info
          pr-number: ${{ github.event.pull_request.number }}
          output-file: test-no-branch.html
          hide-branch-coverage: true
